// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mcwxdlsekmkgsjkzjavc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1jd3hkbHNla21rZ3Nqa3pqYXZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NDAzMjQsImV4cCI6MjA2NTUxNjMyNH0.dGZirH7XbYJvK46s212mB_6AWsrOLRQE9lfYhmhabFQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);